#
#  Makefile for GXemul src/core
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=debugmsg.o emul.o emul_parse.o float_emul.o interrupt.o main.o \
	memory.o misc.o settings.o timer.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile


